site_name: Practica2.6 - Despligue usando Marven & Tomcat
nav:  
  - Home: https://yahyalimouni.github.io
  - Practica2.1: https://yahyalimouni.github.io/practica2/
  - Practica2.2: https://yahyalimouni.github.io/practica2.2/
  - Practica2.3: https://yahyalimouni.github.io/practica2.3/
  - Practica2.4: https://yahyalimouni.github.io/practica2.4/
  - Practica2.5: https://yahyalimouni.github.io/practica2.5/


theme:
  name: material  # Use Material theme for MkDocs
  features:
    - navigation.tabs  # Enable tab navigation
    - navigation.top  # Show navigation at the top
    - search.highlight  
    - search.share  
    - navigation.tracking  


  palette:
    scheme: slate
    primary: cyan
    accent: indigo
